### ISSUE TITLE
ModuleNotFoundError: No module named 'A_NLM_model'.

### ISSUE THREAD

**Issue by WbuerDy** [dbis-ukon/lplm#1]
Dear Author,
Thank you for your ideas. When I was running the experiment, I encountered a ModuleNotFoundError: No module named 'A_NLM_model'. Could you please let me know where I can find this module? Thank you for your contribution.
Best regards.

**Comment by prnm2** [comment]
It has been fixed.

**Comment by prnm2** [comment]
It has been fixed. module name is selectivity_estimator.py.

**Comment by WbuerDy** [comment]
Thank you. I downloaded the old code. I'll try it again, thanks.
