### ISSUE TITLE
    transformedLikepattern = LIKE_pattern_to_newLanguage(line_[0].split('%'), line_[1]) IndexError: list index out of range

### ISSUE THREAD

**Issue by WbuerDy** [dbis-ukon/lplm#2]
Dear author:
It seems that in your latest modified code, you have not passed in the pattern_type parameter, which has led to the error "transformedLikepattern = LIKE_pattern_to_newLanguage(line_[0].split('%'), line_[1]) IndexError: list index out of range". Could this be the issue?

**Comment by prnm2** [comment]
I dont see any issue here.  I run the latest version and there is no issue.

XI_S_AO:suffix:0.03814 0.6825147118802074 0.7478231176370156 0.08789954337899543 0.04025974025974026 0.9032258064516129 0.39285714285714285 0.5454545454545454 1.0 1.0
line_[0].split('%'), line_[1]
As you can see from line above, first parameter is 
XI_S_AO and the second one is suffix.

there must be an issue with your input data.

and for that kind of small issues, please find out by yourself. not happy with my implementation, everything is very clear in the paper. you can implement by yourself. I have a paper to submit. I left like cardinality estimation in the past.

**Comment by WbuerDy** [comment]
Thank you, I wish you all the best in your research!
